//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamInfo()
        {
            this.UserExams = new HashSet<UserExam>();
        }
    
        public int Id { get; set; }
        public int QuizListId { get; set; }
        public Nullable<System.DateTime> DayOpen { get; set; }
        public Nullable<System.DateTime> DayEnd { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Ispublic { get; set; }
    
        public virtual QuizList QuizList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserExam> UserExams { get; set; }
    }
}
