//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExam
    {
        public int UserId { get; set; }
        public int ExamInfoId { get; set; }
        public Nullable<double> ExamPoint { get; set; }
        public Nullable<System.DateTime> TimeEntry { get; set; }
    
        public virtual ExamInfo ExamInfo { get; set; }
        public virtual User User { get; set; }
    }
}
