//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinhvien
    {
        public int Id { get; set; }
        public string Hoten { get; set; }
        public string Khoa { get; set; }
        public string Lop { get; set; }
        public string Giotinh { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Sodienthoai { get; set; }
        public string Thongtinkhac { get; set; }
    }
}
